---
name: MongoDB container example
run-name: MongoDB service container test
on: 
  push:
    branches:
      - 'play-service-container'

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0.4-jammy
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: apinyarr/doct-cbd3324-backend
          github-server-url: 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com'
          ref: refs/tags/v1.0

      - name: List cloned repo
        run: |
          pwd
          ls -alrth
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Install Python Requirements
        run: |
          pip3 install -r requirements.txt
          pip3 freeze

      - name: Run App for DB Connecting Test
        run: python3 app/main.py &

      - name: Test App
        run: curl http://127.0.0.1:8088/search?word=blue