---
name: Publish Maven Packages to GitHub Packages

on:
  push:
    tags:
      - 'v*'

env:
  SEARCH_PATH: com.mycompany.app.App
  SEARCH_JAR: target/my-app-1.0-SNAPSHOT.jar

jobs:
  publish-maven-package:
    permissions:
      packages: 'write'
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # - name: Debug step (will be removed)
      #   run: |
      #     mvn help:evaluate -Dexpression=settings.localRepository
      #     pwd
      #     ls -alrth ~/
      
      - name: Run the Maven verify phase
        run: mvn -f my-app/pom.xml --batch-mode --update-snapshots verify

      - name: Configure M2 Settings
        run: echo '${{secrets.DOT_M2_SETTINGS_XML}}' > /home/runner/.m2/settings.xml

      - name: Packaging
        run: mvn -f my-app/pom.xml package

      - name: Test Application
        run: java -cp ${{env.SEARCH_JAR}} ${{env.SEARCH_PATH}}

      - name: Publish the Package
        run: mvn -f my-app/pom.xml deploy

